esphome:
  name: monitor
  platform: ESP32
  board: nodemcu-32s
  project:
    name: "marshallasch.monitor_backlight"
    version: "1.0.1"

wifi:
  ssid: "78-2.4G"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Monitor Fallback Hotspot"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  ota: false


light:
  - platform: fastled_clockless
    name: "Monitor Light"
    chipset: WS2812
    pin: GPIO13
    num_leds: 32
    rgb_order: GRB
    effects:
        - random:
            name: "random"
        - addressable_rainbow:
            name:  "rainbow"
        - addressable_random_twinkle:
            name: "twinkle"
            twinkle_probability: 10%
        - addressable_flicker:
            name: "flicker"
            intensity: 15.0%
        - addressable_fireworks:
            name: "fireworks"
        - addressable_color_wipe:
            name: "wipe"
            colors:
              num_leds: 3
              random: true
